Repository yesi07111/IS_Project_Playground, pull requests merged in 2024-11, with the labels that each got.

#1 Feat(fe)/add home page and nav bar
  frontend/src/components/features/ActivityCard.tsx
  frontend/src/components/features/StatsSummary.tsx
  frontend/src/components/layouts/Navbar.tsx
  frontend/src/pages/HomePage.tsx
Labels: FE

#2 feat(FE): add Login, Register and Verify Email Pages
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/RegisterPage.tsx
  frontend/src/pages/VerifyEmailPage.tsx
Labels: FE

#3 feat(FE)/update App and Auth management
  frontend/src/App.tsx
  frontend/src/components/auth/ProtectedRoute.tsx
  frontend/src/services/authService.ts
  frontend/src/services/axiosConfig.ts
Labels: FE

#4 feat(BE): updating migrations
  backend/src/Infraestructure/Migrations/Postgres/20241118023321_InitialCreate.Designer.cs
  backend/src/Infraestructure/Migrations/Postgres/20241118023321_InitialCreate.cs
  backend/src/Infraestructure/Migrations/Postgres/DefaultDbContextModelSnapshot.cs
Labels: BE

#5 feat(BE)/update Auth management
  backend/src/Application/Commands/Auth/Register/RegisterCommand.Validator.cs
  backend/src/Infraestructure/Configurations/EmailConfiguration.cs
  backend/src/Infraestructure/Services/EmailSenderService.cs
  backend/src/Infraestructure/Setup.cs
  backend/src/WebApi/Program.cs
  backend/src/WebApi/Setup.cs
  backend/src/WebApi/appsettings.Development.json
Labels: BE

#10 fix(BE): UserSpecification
  backend/src/Domain/Specifications/UserSpecifications.cs
Labels: BE

#8 feat(FE): created Admin Page
  frontend/src/App.tsx
  frontend/src/pages/AdminPage.tsx
Labels: FE

#18 feat(FE)/update auth and package usage
  backend/src/Application/Commands/Auth/ConfirmEmail/ConfirmEmailCommand.Handler.cs
  backend/src/Application/Commands/Auth/ConfirmEmail/ConfirmEmailCommand.Validator.cs
  backend/src/Application/Commands/Auth/Login/LoginCommand.Validator.cs
  backend/src/Application/Commands/Auth/Register/RegisterCommand.Handler.cs
  backend/src/Application/Commands/Auth/Register/RegisterCommand.Validator.cs
  backend/src/Application/Commands/Auth/ResendEmail/ResendEmailCommand.Handler.cs
  backend/src/Application/Queries/Auth/CheckEmail/CheckEmailQuery.Handler.cs
  backend/src/Application/Queries/Auth/CheckEmail/CheckEmailQuery.cs
  backend/src/Application/Queries/Dtos/CheckEmailResponse.cs
  backend/src/Application/Repositories/IRepository.cs
  backend/src/Domain/Entities/Common/IBaseEntity.cs
  backend/src/Domain/Entities/Notification.cs
  backend/src/WebApi/Endpoints/Auth/CheckEmailEndpoint.cs
  backend/src/WebApi/Endpoints/Auth/CleanUpUnverifiedUsersEndpoint.cs
  backend/src/WebApi/Endpoints/Auth/DeleteFailUserEndpoint.cs
  frontend/src/components/auth/UserProfile.tsx
  frontend/src/components/auth/authContext.tsx
  frontend/src/components/layouts/Navbar.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/RegisterPage.tsx
  frontend/src/pages/VerifyEmailPage.tsx
  frontend/src/services/authService.ts
  frontend/src/services/cacheService.js
Labels: FE, BE

#19 feat(FE)/add documentation
  frontend/eslint.config.js
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/components/auth/ProtectedRoute.tsx
  frontend/src/components/auth/UserProfile.tsx
  frontend/src/components/auth/authContext.tsx
  frontend/src/components/features/ActivityCard.tsx
  frontend/src/components/features/StatsSummary.tsx
  frontend/src/components/layouts/GradientText.tsx
  frontend/src/components/layouts/Navbar.tsx
  frontend/src/index.css
  frontend/src/interfaces/Activity.tsx
  frontend/src/interfaces/ActivityCardProps.tsx
  frontend/src/interfaces/AuthContextType.tsx
  frontend/src/interfaces/AuthProviderProps.tsx
  frontend/src/interfaces/ProtectedRouteProps.tsx
  frontend/src/interfaces/RegisterData.tsx
  frontend/src/main.tsx
  frontend/src/pages/AdminPage.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/RegisterPage.tsx
  frontend/src/pages/UserTypePage.tsx
  frontend/src/pages/VerifyEmailPage.tsx
  frontend/src/services/authService.ts
  frontend/src/services/cacheService.js
  frontend/src/types/FieldErrors.ts
  frontend/src/types/FieldGeneralErrors.ts
  frontend/src/types/declarations.d.ts
  frontend/src/types/images.d.ts
  frontend/src/vite-env.d.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: documentation
