Repository yesi07111/IS_Project_Playground, pull requests merged in 2025-01, with the labels that each got.

#44 fix(BE/FE)/Register and VerifyEmail
  backend/src/Application/Commands/Auth/DeleteFailUser/DeleteFailUserCommand.Handler.cs
  backend/src/Application/Commands/Auth/Register/RegisterCommand.Handler.cs
  backend/src/Application/Commands/Auth/Register/RegisterCommand.Validator.cs
  backend/src/Application/Queries/Activity/Get/GetActivityQuery.Handler.cs
  backend/src/Application/Queries/Activity/List/ListActivityQuery.Handler.cs
  backend/src/Application/Repositories/IRepository.cs
  backend/src/Domain/SmartEnum/FacilityImageSmartEnum.cs
  backend/src/Domain/SmartEnum/UseCaseSmartEnum.cs
  backend/src/Infraestructure/Data/Repositories/Repository.cs
  backend/src/WebApi/Endpoints/Activity/GetActivityEndpoint.cs
  backend/src/WebApi/Endpoints/Auth/DeleteFailUserEndpoint.cs
  backend/src/WebApi/Seeder.cs
  frontend/src/interfaces/RegisterData.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/RegisterPage.tsx
  frontend/src/pages/VerifyEmailPage.tsx
  frontend/src/services/activityService.ts
  frontend/src/services/authService.ts
  frontend/src/services/facilityService.ts
Labels: bug, FE, BE

#46 feat(BE): add role name to login
  backend/src/Application/Commands/Auth/ConfirmEmail/ConfirmEmailCommand.Handler.cs
  backend/src/Application/Commands/Auth/Login/LoginCommand.Handler.cs
  backend/src/Application/Commands/Responses/UserActionResponse.cs
  frontend/src/interfaces/UserActionResponse.tsx
Labels: BE

#57 feat(FE/BE): users and facilities query
  backend/src/Application/Queries/Facility/List/ListFacilityQuery.Handler.cs
  backend/src/Domain/SmartEnum/UseCaseSmartEnum.cs
  frontend/src/App.tsx
  frontend/src/components/auth/UserProfile.tsx
  frontend/src/components/features/GenericCard.tsx
  frontend/src/components/features/ResourceCard.tsx
  frontend/src/components/layouts/Navbar.tsx
  frontend/src/interfaces/GenericCardProps.tsx
  frontend/src/pages/AdminPage.tsx
  frontend/src/pages/FacilitiesPage.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/ResourcesPage.tsx
  frontend/src/pages/UserManagementPage.tsx
  frontend/src/pages/UsersPage.tsx
  frontend/src/services/cacheService.ts
Labels: FE, BE

#58 feat(BE/FE)/add unit tests and reservation functionality
  .gitignore
  backend/src/Application/Commands/Reservation/Cancel/CancelReservationCommand.Handler.cs
  backend/src/Application/Commands/Reservation/Cancel/CancelReservationCommand.cs
  backend/src/Application/Commands/Reservation/Create/CreateReservationCommand.Handler.cs
  backend/src/Application/Commands/Reservation/Create/CreateReservationCommand.cs
  backend/src/Application/Queries/Reservation/ListReservationQuery.Handler.cs
  backend/src/Application/Queries/Reservation/ListReservationQuery.cs
  backend/src/Domain/SmartEnum/ReservationStateSmarEnum.cs
  backend/src/Domain/Specifications/ActivityDateSpecifications.cs
  backend/src/Domain/Specifications/ActivitySpecifications.cs
  backend/src/Domain/Specifications/BaseSpecifications/AndSpecification.cs
  backend/src/Domain/Specifications/BaseSpecifications/ISpecification.cs
  backend/src/Domain/Specifications/BaseSpecifications/NotSpecification.cs
  backend/src/Domain/Specifications/BaseSpecifications/OrSpecification.cs
  backend/src/Domain/Specifications/FacilitySpecifications.cs
  backend/src/Domain/Specifications/ReservationSpecifications.cs
  backend/src/Domain/Specifications/ResourceDateSpecifications.cs
  backend/src/Domain/Specifications/ResourceSpecifications.cs
  backend/src/Domain/Specifications/ReviewSpecifications.cs
  backend/src/Domain/Specifications/RolSpecifications.cs
  backend/src/Domain/Specifications/UserProfileImagesSpecifications.cs
  backend/src/Domain/Specifications/UserSpecifications.cs
  backend/src/Infraestructure/Data/Repositories/Repository.cs
  backend/src/Infraestructure/Factories/RepositoryFactory.cs
  backend/src/Infraestructure/Services/CleanUpService.cs
  backend/src/Infraestructure/Services/CodeGenerator.cs
  backend/src/Infraestructure/Services/CommentsService.cs
  backend/src/Infraestructure/Services/ConverterService.cs
  backend/src/Infraestructure/Services/InMemoryEventPublisher.cs
  backend/src/Infraestructure/Services/NotificationService.cs
  backend/src/Tests/Repository/RepositoryFactoryUnitTests.cs
  backend/src/Tests/Repository/RepositoryUnitTests.cs
  backend/src/Tests/Services/AccessFailedServiceUnitTests.cs
  backend/src/Tests/Services/ActiveSessionServiceUnitTest.cs
  backend/src/Tests/Services/Cascaron.cs
  backend/src/Tests/Services/CleanUpServiceUnitTests.cs
  backend/src/Tests/Services/CodeGeneratorServiceUnitTests.cs
  backend/src/Tests/Services/CommentsServiceUnitTests.cs
  backend/src/Tests/Services/ConverterServiceUnitTests.cs
  backend/src/Tests/Services/DateTimeServiceUnitTests.cs
  backend/src/Tests/Services/EmailSenderServiceUnitTests.cs
  backend/src/Tests/Services/ImageServiceUnitTests.cs
  backend/src/Tests/Services/InMemoryEventPublisherUnitTests.cs
  backend/src/Tests/Services/JwtGeneratorServiceUnitTests.cs
  backend/src/Tests/Services/LoginProviderServiceUnitTests.cs
  backend/src/Tests/Services/NotificationServiceUnitTests.cs
  backend/src/Tests/Services/RatingServiceUnitTests.cs
  backend/src/Tests/Tests.csproj
  backend/src/WebApi/Endpoints/Reservation/CancelReservationEndpoint.cs
  backend/src/WebApi/Endpoints/Reservation/CreateReservationEndpoint.cs
  frontend/src/pages/MyReservationPage.tsx
  frontend/src/services/activityService.ts
  frontend/src/services/reservationService.ts
Labels: FE, BE

#56 feat(FE/BE): adding details to educator
  backend/src/Application/Commands/Activity/Create/CreateActivityCommand.cs
  backend/src/Application/Commands/Activity/Create/CreateActivityCommandHandler.cs
  backend/src/Application/Commands/Activity/Create/CreateActivityCommandValidator.cs
  backend/src/Application/Commands/ResourceDate/CreateResourceDateCommand.cs
  backend/src/Application/Commands/ResourceDate/CreateResourceDateCommandHandler.cs
  backend/src/Application/Commands/ResourceDate/CreateResourceDateCommandValidator.cs
  backend/src/Application/Commands/UsageFrequency/PostUsageFrequencyCommandValidator.cs
  backend/src/Application/Queries/Activity/List/ListActivityQuery.Handler.cs
  backend/src/Application/Queries/Activity/List/ListActivityQuery.cs
  backend/src/Application/Queries/Dtos/ResourceDateDto.cs
  backend/src/Application/Queries/Reponses/ListResourceDateResponse.cs
  backend/src/Application/Queries/ResourceDate/ListResourceDateQuery.Handler.cs
  backend/src/Application/Queries/ResourceDate/ListResourceDateQuery.cs
  backend/src/WebApi/Endpoints/Activity/CreateActivityEndPoint.cs
  backend/src/WebApi/Endpoints/Resource/PostUsageFrequencyEndPoint.cs
  backend/src/WebApi/Endpoints/ResourceDate/CreateResourceDateEndPoint.cs
  backend/src/WebApi/Endpoints/ResourceDate/ListResourceDateEndPoint.cs
  frontend/src/App.tsx
  frontend/src/components/features/BarsChart.tsx
  frontend/src/components/features/LinesChart.tsx
  frontend/src/components/features/PiesChart.tsx
  frontend/src/components/features/StyledFiltersResource.tsx
  frontend/src/components/layouts/Navbar.tsx
  frontend/src/interfaces/Facility.tsx
  frontend/src/interfaces/FacilityResponse.tsx
  frontend/src/interfaces/Filters.tsx
  frontend/src/interfaces/PlotProps.tsx
  frontend/src/interfaces/Resource.tsx
  frontend/src/interfaces/ResourceCardProps.tsx
  frontend/src/interfaces/ResourceDate.tsx
  frontend/src/interfaces/ResourceFilters.tsx
  frontend/src/pages/ActivitiesPage.tsx
  frontend/src/pages/ActivityFormPage.tsx
  frontend/src/pages/ResourcesPage.tsx
  frontend/src/pages/StatisticsPage.tsx
  frontend/src/pages/UsageFrequencyPage.tsx
  frontend/src/services/activityService.ts
  frontend/src/services/cacheService.ts
  frontend/src/services/resourceService.ts
Labels: FE, BE

#60 Feat(be/fe)/admin user management
  backend/src/Application/Commands/User/Create/CreateUserCommand.Handler.cs
  backend/src/Application/Commands/User/Create/CreateUserCommand.Validator.cs
  backend/src/Application/Commands/User/Create/CreateUserCommand.cs
  backend/src/Application/Commands/User/Delete/DeleteUserCommand.cs
  backend/src/Application/Commands/User/Delete/DeleteUserCommandHandler.cs
  backend/src/WebApi/Endpoints/User/CreateUserEndPoint.cs
  backend/src/WebApi/Endpoints/User/DeleteUserEndPoint.cs
  frontend/src/App.tsx
  frontend/src/components/features/GenericCard.tsx
  frontend/src/interfaces/User.tsx
  frontend/src/pages/UserFormPage.tsx
  frontend/src/pages/UsersPage.tsx
  frontend/src/services/userService.ts
Labels: FE, BE

#61 fix(BE/FE)/unit test recaptcha and services
  backend/src/Application/Commands/Review/Delete/DeleteReviewCommand.Handler.cs
  backend/src/Application/Queries/Activity/Get/GetActivityQuery.Handler.cs
  backend/src/Infraestructure/Services/CommentsService.cs
  backend/src/Tests/EndPoints/Activity/CreateActivityEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Activity/GetActivityEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Activity/ListActivityEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Activity/ReserveActivityEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/CheckEmailEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/CheckGoogleTokenEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/CleanUpUnverifiedUsersEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/ConfirmEmailEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/DecodeTokenEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/DeleteFailUserEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/GetGoogleClientIdEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/GetReCaptchaSiteKeyEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/GoogleAccessEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/LoginEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/RefreshTokenEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/RegisterEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/ResendEmailEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/ResetPasswordEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/SendResetPasswordEmailEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/UploadUserImageEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Auth/VerifyRecaptchaEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Facility/ListFacilityEndpointUnitTests.cs
  backend/src/Tests/EndPoints/HomePage/GetHomePageInfoEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Reservation/ListReservationEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Resource/ListResourceEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Resource/UpdateUsageFrequencyEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Review/CreateReviewEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Review/DeleteReviewEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Review/ListReviewEndpointUnitTests.cs
  backend/src/Tests/EndPoints/Review/UpdateReviewEndpointUnitTests.cs
  backend/src/Tests/EndPoints/User/GetUserEndpointUnitTests.cs
  backend/src/Tests/EndPoints/User/ListUserEndpointUnitTests.cs
  backend/src/Tests/EndPoints/User/UpdateUserEndpointUnitTests.cs
  backend/src/Tests/Services/CommentsServiceUnitTests.cs
  frontend/src/App.tsx
  frontend/src/pages/MyReservationPage.tsx
  frontend/src/pages/RegisterPage.tsx
Labels: FE, BE
